name: secret-to-env-workflow
on: push
jobs:
  copy-secrets-to-env:
    runs-on: ubuntu-latest
    steps:
      - name: retrieve secret
        env:
          wordle_graph_pat: ${{ secrets.WORDLE_GRAPH_PAT }}
